title: Ruby Diagrams
description: A simple Ruby DSL to write a Graphviz dot file of clould architecture diagrams.
theme: just-the-docs

color_scheme: dark

url: https://g-omahony.github.io/diagrams-rb-docs

aux_links:
  Github: https://github.com/g-omahony/diagrams-rb

enable_copy_code_button: true

sass:
  quiet_deps: true
